// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa6JLMat7COcrF0xctcNjwZPCPo-DVtAY',
    appId: '1:470611767220:web:ccaad520555313faeb4ce1',
    messagingSenderId: '470611767220',
    projectId: 'teacherapp-d8da6',
    authDomain: 'teacherapp-d8da6.firebaseapp.com',
    storageBucket: 'teacherapp-d8da6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ_Ap0aWZI1OZoVlTCRW5CMS__mmGNY8k',
    appId: '1:470611767220:android:ea89eb4e105eae82eb4ce1',
    messagingSenderId: '470611767220',
    projectId: 'teacherapp-d8da6',
    storageBucket: 'teacherapp-d8da6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiojchf7QdKG9IJgA7039P_22kZb77Xi0',
    appId: '1:470611767220:ios:2d02567fc9b25c9beb4ce1',
    messagingSenderId: '470611767220',
    projectId: 'teacherapp-d8da6',
    storageBucket: 'teacherapp-d8da6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiojchf7QdKG9IJgA7039P_22kZb77Xi0',
    appId: '1:470611767220:ios:2d02567fc9b25c9beb4ce1',
    messagingSenderId: '470611767220',
    projectId: 'teacherapp-d8da6',
    storageBucket: 'teacherapp-d8da6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa6JLMat7COcrF0xctcNjwZPCPo-DVtAY',
    appId: '1:470611767220:web:4a8996187e978e37eb4ce1',
    messagingSenderId: '470611767220',
    projectId: 'teacherapp-d8da6',
    authDomain: 'teacherapp-d8da6.firebaseapp.com',
    storageBucket: 'teacherapp-d8da6.firebasestorage.app',
  );
}
